# Generated by Django 4.1.13 on 2024-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('Title', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('AnnouncementCode', models.CharField(blank=True, max_length=100, null=True)),
                ('Term', models.CharField(max_length=100)),
                ('Eligibility', models.TextField()),
                ('Audience', models.CharField(max_length=200)),
                ('StartDate', models.DateField()),
                ('Duration', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('JobDescription', models.TextField()),
                ('JobRequirement', models.TextField()),
                ('RequiredQual', models.TextField()),
                ('Salary', models.CharField(max_length=100)),
                ('ApplicationP', models.TextField()),
                ('OpeningDate', models.DateField()),
                ('Deadline', models.DateField()),
                ('Notes', models.TextField(blank=True, null=True)),
                ('AboutC', models.TextField()),
                ('Attach', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('IT', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('sexe', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('diplome', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('cv', models.FileField(upload_to='cvs/')),
            ],
        ),
    ]
