# Generated by Django 4.1.13 on 2024-05-18 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('Title', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('AnnouncementCode', models.CharField(blank=True, max_length=100, null=True)),
                ('Term', models.CharField(max_length=100)),
                ('Eligibility', models.TextField()),
                ('Audience', models.CharField(max_length=200)),
                ('StartDate', models.DateField()),
                ('Duration', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('JobDescription', models.TextField()),
                ('JobRequirement', models.TextField()),
                ('RequiredQual', models.TextField()),
                ('Salary', models.CharField(max_length=100)),
                ('ApplicationP', models.TextField()),
                ('OpeningDate', models.DateField()),
                ('Deadline', models.DateField()),
                ('Notes', models.TextField(blank=True, null=True)),
                ('AboutC', models.TextField()),
                ('Attach', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('IT', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.joboffre')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Offre',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
