# Generated by Django 4.1.13 on 2024-05-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_joboffre_recommendation_appuser_delete_offre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOffre',
            new_name='Job',
        ),
    ]
