# Generated by Django 4.1.13 on 2024-05-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_rename_joboffre_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='job_offer',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
