# Generated by Django 4.1.13 on 2024-05-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_post_remove_recommendation_job_offer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
